### ISSUE TITLE
Errors upon loading.

### ISSUE THREAD

**Issue by imj0seph** [jahendrie/qytdl#1]
I have compiled the qytdl package from the AUR.

Program does not load, here is what is displayed upon entering 'qytdl' into the terminal:

```
Traceback (most recent call last):
  File "/usr/share/qytdl/src/config.py", line 111, in read_config
    fp = open( cfg, "r" )
FileNotFoundError: [Errno 2] No such file or directory: '/home/joseph/.config/qytdl/config.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 29, in <module>
    from mainWindow import MainWindow
  File "/usr/share/qytdl/src/mainWindow.py", line 13, in <module>
    class MainWindow( QMainWindow ):
  File "/usr/share/qytdl/src/mainWindow.py", line 15, in MainWindow
    opts = read_config()
  File "/usr/share/qytdl/src/config.py", line 116, in read_config
    create_config( path, opts )
NameError: name 'path' is not defined
```

All dependencies are satisfied.
I am currently on 4.14.13-1-ARCH.

**Comment by jahendrie** [comment]
Alright, I think I've fixed it.  Thanks for pointing it out, and if there are other issues, don't be shy about letting me know.

**Comment by imj0seph** [comment]
Thank you, the error has been rectified.
:)
