### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by HellishINC** [jahendrie/qytdl#4]
python 3.8.2
python-pyqt5 5.14.2
youtube-dl 2020.03.24
```
Traceback (most recent call last):
  File "src/main.py", line 29, in <module>
    from main_window import MainWindow
  File "/home/kimoli/.tmp/qytdl/src/main_window.py", line 15, in <module>
    class MainWindow( QMainWindow ):
  File "/home/kimoli/.tmp/qytdl/src/main_window.py", line 18, in MainWindow
    profiles = read_profiles()
  File "/home/kimoli/.tmp/qytdl/src/profile.py", line 349, in read_profiles
    profiles, examples = parse_profiles( fp )
  File "/home/kimoli/.tmp/qytdl/src/profile.py", line 325, in parse_profiles
    et = ET.parse( fp )
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 39, column 0
```

**Comment by jahendrie** [comment]
Okay, try removing the config files from ~/.config/qytdl and starting it again.  It should re-write the defaults.

**Comment by HellishINC** [comment]
That was the first run.

Deleting contents still causes the same error.

```
 ~ 
 01:47:28 PM   >> $ rm -Rf ~/.config/qytdl
 ~ 
 01:47:58 PM   >> $ qytdl 
Traceback (most recent call last):
  File "/usr/share/qytdl/src/profile.py", line 348, in read_profiles
    fp = open( profilePath, "r" )
FileNotFoundError: [Errno 2] No such file or directory: '/home/kimoli/.config/qytdl/profiles.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 29, in <module>
    from main_window import MainWindow
  File "/usr/share/qytdl/src/main_window.py", line 15, in <module>
    class MainWindow( QMainWindow ):
  File "/usr/share/qytdl/src/main_window.py", line 18, in MainWindow
    profiles = read_profiles()
  File "/usr/share/qytdl/src/profile.py", line 354, in read_profiles
    create_profiles( profilePath, defaults, examples )
  File "/usr/share/qytdl/src/profile.py", line 300, in create_profiles
    pro.write( fp )
  File "/usr/share/qytdl/src/profile.py", line 165, in write
    self.write_post_processors( fp )
  File "/usr/share/qytdl/src/profile.py", line 111, in write_post_processors
    fp.write( "\t\t\t\t%s:%s,\n" % (key, self.pp[ key ]))
AttributeError: 'Profile' object has no attribute 'pp'
 ~ 
 01:48:03 PM   >> $ 

```

**Comment by jahendrie** [comment]
Alright.  Try updating your installation and give it another shot.

**Comment by HellishINC** [comment]
No go. Perhaps py3.8.2 is too recent?

```
 /tmp/qytdl-master/src 
 09:32:55 PM   >> $ python main.py 
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    from main_window import MainWindow
  File "/tmp/qytdl-master/src/main_window.py", line 15, in <module>
    class MainWindow( QMainWindow ):
  File "/tmp/qytdl-master/src/main_window.py", line 18, in MainWindow
    profiles = read_profiles()
  File "/tmp/qytdl-master/src/profile.py", line 349, in read_profiles
    profiles, examples = parse_profiles( fp )
  File "/tmp/qytdl-master/src/profile.py", line 325, in parse_profiles
    et = ET.parse( fp )
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 39, column 0

```
